### PR TITLE
Fix Visual Studio 2015 issue (snprintf not found)

### PR DESCRIPTION
**Pull request by Chabster**
@akheron Please review and merge.

### CODE REVIEW

**Comment by akheron** [comment]
Is this still required in addition to https://github.com/akheron/jansson/blob/8f2298bad8f77a22efe0dc9a95676fae6c203e36/cmake/jansson_private_config.h.cmake#L52-L64 ?

**Comment by Chabster** [comment]
@akheron The fix you mentioned is for Visual Studio 2013 and lower.
This fixes Visual Studio 2015 and higher (https://cmake.org/Bug/view.php?id=15659 - related bug/issue).

**Comment by akheron** [comment]
I don't think this is the correct fix. `src/jansson_private.h` does all the checking and defining needed for visual studio workarounds. Everything else related to snprintf and vsnprintf should be removed from `CMakeLists.txt` and `cmake/jansson_private_config.h.cmake`.

**Comment by akheron** [comment]
@Chabster could you check whether changes in #289 work for you?

**Comment by akheron** [comment]
Should be fixed by #289

**Pull request closed without merging**
