### PR TITLE
Add json_object_update_recursive()

### PR DESCRIPTION
**Pull request by hmpcabral**
Support merging values nested within objects. For instance, merging:

```json
    {
	"foo": 1,
	"bar": {
	    "baz": 2
	}
    }
```

with

```json
    {
	"bar": {
	    "baz": 3
	}
    }
```

results in

```json
    {
	"foo": 1,
	"bar": {
	    "baz": 3
	}
    }
```

instead of overwriting the value for the bar key.

### CODE REVIEW

**Comment by coreyfarrell** [comment]
Thank you for this contribution.  I'd like to point you to #457 to mention that this new function also suffers from risk of infinite loop if it encounters a circular reference.  Potentially an issue for `object` and `other`.  Also concerning to me - what happens if `object` and `other` both reference the same sub-object, or if `other` contains two references to the same object?  As is this function risks editing part of `other` while updating `object`.

I think I'd want to see this split into public facing and private function.  The public function would check for both arguments being objects and check that no object members are referenced more than once between `object` and `other`.

**Comment by harkue** [comment]
"json_deep_copy infinite loop" has been resolved in PR #490 .

**Comment by coreyfarrell** [comment]
Thanks for the ping on this issue, if this is updated to incorporate the loop checks from #490 I can take another look.

**Comment by AllenX2018** [comment]
I can create a pr based on this one incorporating loop check from #490 if needed.

**Comment by AllenX2018** [comment]
@coreyfarrell Do you mean adding new commits to @hmpcabral's branch? I'm afraid I can't do that since I don't have write access to his fork.

**Comment by ploxiln** [comment]
You can duplicate his branch into your own fork, and then add to it there.

**Comment by ploxiln** [comment]
(and the commits will retain the current author metadata)

**Comment by AllenX2018** [comment]
@ploxiln Thanks! I'll try

**Comment by akheron** [comment]
Fixed in #505

**Pull request closed without merging**
