### PR TITLE
Fix for issue #282

### PR DESCRIPTION
**Pull request by dev-zzo**
The fix limits recursion depths when parsing arrays and objects, avoiding stack exhaustion and a crash. The limit is configurable via the `JSON_PARSER_MAX_DEPTH` setting within `jansson_config.h`.

Reported by Gustavo Grieco.

### CODE REVIEW

**Comment by dev-zzo** [comment]
Apparently, Windows builds can't handle the depth of 16384 inlaid arrays.

**Comment by dev-zzo** [comment]
Please review.

**Comment by akheron** [comment]
Thanks for a quick fix!

I think you should also decrement the depth in the end of `parse_value`. Without decrementing it, an array containing 2048 flat objects generates the maximum depth error, right?

This should also be documented in the RFC compliance section.

**Comment by dev-zzo** [comment]
Excellent points. I should have done that in the first place.

Please review.

**Comment by akheron** [comment]
LGTM. Can you squash this to a single commit before merge?

**Comment by dev-zzo** [comment]
Closing this pull request; please use pull request #284.

**Pull request closed without merging**
