### PR TITLE
GitHub Actions

### PR DESCRIPTION
**Pull request by akheron**
Move from Travis to GitHub actions. Keep AppVeyor to build on older Visual Studio versions, too.

### CODE REVIEW

**Comment by ploxiln** [comment]
just for macOS+autotools, it appears you need to add a step like:

```
    run: brew install automake autoconf
```

also, it looks like the plain "build" step of the autotools job is missing, not sure if that's intentional

**Comment by akheron** [comment]
There’s a lot still missing. My goal is to finish this in the near future :)

**Comment by akheron** [comment]
I think everything else except ossfuzz is now included

**Comment by akheron** [comment]
Decided to keep AppVeyor because GitHub actions only seems to support the newest Visual Studio.

**Review by SamyDgz — APPROVED** [review]

**Pull request merged**
